{% set name = "uncertainties" %}
{% set version = "3.1.4" %}
{% set sha256 = "63548a94899f2a51eeb89b640f6ac311f481a8016b37dce157186e44619bc968" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/u/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - numpy

test:
  requires:
    - numpy
  imports:
    - {{ name }}
    - {{ name }}.unumpy

about:
  home: https://pypi.python.org/pypi/uncertainties
  license: BSD 3-Clause
  license_file: LICENSE.txt
  summary: Transparent calculations with uncertainties on the quantities involved (aka "error propagation"); fast calculation of derivatives.
