{% set name = "uncertainties" %}
{% set version = "3.1.5" %}
{% set sha256 = "9122c1e7e074196883b4a7a946e8482807b2f89675cb5e3798b87e0608ede903" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - future
    - numpy

test:
  requires:
    - numpy
  imports:
    - {{ name }}
    - {{ name }}.unumpy

about:
  home: https://pypi.python.org/pypi/uncertainties
  license: BSD 3-Clause
  license_file: LICENSE.txt
  summary: Transparent calculations with uncertainties on the quantities involved (aka "error propagation"); fast calculation of derivatives.
